### ISSUE TITLE
Days of the week in meal plan disappear

### ISSUE THREAD

**Issue by anurgj** [SE-Fall24-RZA/Recipe_Recommender#24]
Prolly an error in the backend

**Comment by robbiethomas1101** [comment]
This issue seems to occur after attempting to add a recipe to the meal plan without actually selecting a recipe

**Comment by robbiethomas1101** [comment]
The issue was caused by a missed check for improper values in the backend and an incorrect default selection when adding a recipe to the meal plan.  Checks have been added to the frontend and backend to prevent users from attempting to add a recipe to their meal plan before selecting one.

Resolved in pull request #25
